FROM npclown/foundation:1.0
MAINTAINER PNU PNU@PNU.COM

RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:webupd8team/java
RUN apt-get update
RUN apt-get install -y default-jdk
RUN rm -rf /var/lib/apt/lists/*

