FROM npclown/foundation:1.0
MAINTAINER PNU PNU@PNU.COM

RUN apt-get install -y gnustep
RUN apt-get install -y gnustep-devel
RUN apt-get install -y gobjc
RUN apt-get install -y gobjc++
RUN rm -rf /var/lib/apt/lists/*

